Repository rancher/fleet, pull requests merged in 2022-08, with the labels that each got.

#860 Create CODEOWNERS
  CODEOWNERS
Labels: skip-changelog

#894 Consistenly use cattle-fleet-system as namespace
  .github/scripts/deploy-fleet.sh
  .github/workflows/e2e-ci.yml
  .github/workflows/e2e-multicluster-ci.yml
  DEVELOPING.md
  README.md
  charts/fleet-agent/values.yaml
  charts/fleet/values.yaml
  cmd/fleetcontroller/main.go
  docs/agent-initiated.md
  docs/gitrepo-add.md
  docs/multi-cluster-install.md
  docs/namespaces.md
  docs/quickstart.md
  docs/single-cluster-install.md
  docs/troubleshooting.md
  docs/uninstall.md
  docs/webhook.md
  modules/cli/cmds/root.go
  pkg/config/config.go
Labels: [zube]: Review

#901 Merge depandabot prs
  go.mod
  go.sum
  package/Dockerfile
  package/Dockerfile.agent
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: dependencies

#858 Add Fleet issue template
  .github/ISSUE_TEMPLATE/1-bug-report.yml
  .github/ISSUE_TEMPLATE/2-feature-request.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: skip-changelog

#859 Create pull request template
  .github/pull_request_template.md
Labels: skip-changelog
