Repository rancher/fleet, pull requests merged in 2024-06, with the labels that each got.

#2477 Fixes infinite job generation after ForceSyncGeneration changed
  integrationtests/gitjob/controller/controller_test.go
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Labels: kind/bug

#2475 Moves functionality from gitrepo to gitjob controller
  charts/fleet/templates/rbac_gitjob.yaml
  integrationtests/controller/gitrepo/gitrepo_test.go
  integrationtests/gitjob/controller/controller_test.go
  integrationtests/gitjob/controller/suite_test.go
  internal/cmd/controller/errorutil/errorutil.go
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
  internal/cmd/controller/gitrepo/status.go
  internal/cmd/controller/reconciler/cluster_controller.go
  internal/cmd/controller/reconciler/clustergroup_controller.go
  internal/cmd/controller/reconciler/gitrepo_controller.go
Labels: kind/refactor

#2509 Fixes flaky agent integration test
  integrationtests/agent/bundle_deployment_status_test.go
Labels: area/ci

#2517 [0.9] Honor Helm's MaxHistory when using drift correction
  e2e/drift/drift_test.go
  internal/cmd/agent/deployer/monitor.go
  internal/helmdeployer/deployer.go
Labels: JIRA

#2522 Ignore status fields during drift detection
  e2e/assets/drift/correction-enabled/gitrepo.yaml
  e2e/drift/drift_test.go
  internal/cmd/agent/deployer/normalizers/norm.go
  internal/cmd/agent/deployer/normalizers/status.go
  internal/cmd/agent/deployer/normalizers/status_test.go
Labels: area/drift

#2542 Fixes error display and improves user experience in git poller
  pkg/durations/durations.go
  pkg/git/poll/gitrepopolljob.go
  pkg/git/poll/gitrepopolljob_test.go
  pkg/git/poll/handler.go
  pkg/git/poll/handler_test.go
Labels: kind/bug

#2537 Merges gitrepo and gitops controllers
  charts/fleet/templates/deployment.yaml
  charts/fleet/templates/deployment_gitjob.yaml
  charts/fleet/templates/rbac_gitjob.yaml
  charts/fleet/templates/service_gitjob.yaml
  e2e/assets/metrics/service.yaml
  e2e/metrics/gitrepo_test.go
  e2e/metrics/suite_test.go
  e2e/single-cluster/delete_namespaces_test.go
  e2e/single-cluster/finalizers_test.go
  e2e/single-cluster/imagescan_test.go
  e2e/single-cluster/sharding_test.go
  e2e/single-cluster/status_test.go
  integrationtests/controller/cluster/suite_test.go
  integrationtests/controller/gitrepo/gitrepo_test.go
  integrationtests/controller/gitrepo/status_test.go
  integrationtests/controller/gitrepo/suite_test.go
  integrationtests/gitjob/controller/controller_test.go
  integrationtests/gitjob/controller/suite_test.go
  internal/cmd/controller/finalize/finalize.go
  internal/cmd/controller/gitops/operator.go
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
  internal/cmd/controller/gitops/reconciler/gitjob_test.go
  internal/cmd/controller/grutil/status.go
  internal/cmd/controller/operator.go
  internal/cmd/controller/reconciler/bundle_controller.go
  internal/cmd/controller/reconciler/gitrepo_controller.go
  internal/cmd/controller/root.go
  internal/metrics/metrics.go
Labels: kind/refactor
