Repository rancher/fleet, pull requests merged in 2024-04, with the labels that each got.

#2269 CI bumps golangci-lint and uses typos 1.19.0
  .github/workflows/golangci-lint.yml
  .github/workflows/typos.yaml
  .golangci.json
Labels: area/ci

#2268 CI bumps golangci-lint and uses typos 1.19.0
  .github/workflows/golangci-lint.yml
  .github/workflows/typos.yaml
  .golangci.json
Labels: area/ci

#2273 [Backport 0.9] CI: Revert typos back to master
  .github/workflows/typos.yaml
Labels: area/ci

#2272 CI: Revert typos back to master
  .github/workflows/typos.yaml
  _typos.toml
Labels: area/ci

#2267 Adds extra e2e test to check status display
  e2e/assets/single-cluster/helm-status-check.yaml
  e2e/single-cluster/single_cluster_test.go
Labels: area/testing

#2045 Add missing serviceName in fleet-agent statefulset
  charts/fleet-agent/templates/deployment.yaml
  charts/fleet-agent/templates/service.yaml
  e2e/single-cluster/sharding_test.go
  internal/cmd/controller/agentmanagement/agent/manifest.go
Labels: kind/bug

#2326 Update dev/README Dockerfile for act container image
  dev/README.md
Labels: kind/bug

#2189 Add developer docs for monitoring
  dev/README.md
Labels: area/documentation
