Repository rancher/fleet, pull requests merged in 2024-09, with the labels that each got.

#2791 Fixes status not being populated to cluster and clustergroups
  e2e/single-cluster/status_test.go
  internal/cmd/controller/reconciler/cluster_controller.go
Labels: kind/bug

#2821 [v0.10] Fixes finalizer deletion in bundle deployments
  internal/cmd/controller/reconciler/bundledeployment_controller.go
Labels: kind/bug, kind/backport

#2841 Adds e2e test to check that bundledeployments are deleted
  e2e/assets/multi-cluster/bundle-deployment-labels.yaml
  e2e/multi-cluster/not_matching_targets_delete_bd_test.go
  e2e/testenv/env.go
  e2e/testenv/kubectl/kubectl.go
Labels: area/testing

#2872 Deletes retries in the gitops job.
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Labels: kind/enhancement

#2679 BundleDeployment status error message improvement
  charts/fleet-crd/templates/crds.yaml
  integrationtests/agent/adoption_test.go
  integrationtests/agent/bundle_deployment_drift_test.go
  integrationtests/agent/bundle_deployment_status_test.go
  integrationtests/agent/helm_capabilities_test.go
  integrationtests/agent/suite_test.go
  internal/cmd/agent/deployer/monitor/updatestatus.go
  internal/cmd/agent/operator.go
  pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go
Labels: kind/bug
