Repository rancher/fleet, pull requests merged in 2024-07, with the labels that each got.

#2591 Deletes `Bundles` after deleting all its `BundleDeployments`
  internal/cmd/controller/finalize/finalize.go
Labels: kind/bug

#2595 Make gitops controller exit when losing leader lease
  internal/cmd/controller/gitops/operator.go
Labels: kind/bug

#2597 Gitopts reconciler just deletes the Bundle, not BundleDeployments
  internal/cmd/controller/finalize/finalize.go
Labels: kind/enhancement

#2486 [SURE-8456] fix: add owner reference to cluster registration request
  internal/cmd/controller/agentmanagement/controllers/cluster/controller.go
  internal/cmd/controller/agentmanagement/controllers/clusterregistration/controller.go
  internal/cmd/controller/agentmanagement/controllers/clusterregistration/controller_test.go
Labels: kind/bug, JIRA

#2617 Adds support for folder/* patterns in .fleetignore
  internal/bundlereader/loaddirectory.go
  internal/bundlereader/loaddirectory_test.go
Labels: kind/bug

#2643 Use RequeueAfter for Gitpolling job.
  charts/fleet-crd/templates/crds.yaml
  e2e/single-cluster/gitrepo_polling_disabled_test.go
  e2e/single-cluster/gitrepo_test.go
  integrationtests/gitjob/controller/controller_test.go
  integrationtests/gitjob/controller/suite_test.go
  internal/cmd/controller/gitops/operator.go
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
  internal/cmd/controller/gitops/reconciler/gitjob_test.go
  pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
  pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
  pkg/git/mocks/scheduledjob_mock.go
  pkg/git/mocks/scheduler_mock.go
  pkg/git/poll/gitrepopolljob.go
  pkg/git/poll/gitrepopolljob_test.go
  pkg/git/poll/handler.go
  pkg/git/poll/handler_test.go
  pkg/git/poll/suite_test.go
Labels: kind/enhancement, kind/bug

#2660 Changes post render error when using targetNamespace or namespace
  internal/helmdeployer/postrender.go
Labels: kind/enhancement

#2681 Fixes a gitrepo conditions flaky test
  integrationtests/gitjob/controller/controller_test.go
  internal/cmd/controller/grutil/status.go
Labels: kind/enhancement
