Repository rancher/fleet, pull requests merged in 2025-01, with the labels that each got.

#3196 [backport v2.9] [SURE-9137] Add template errors to bundle and gitrepo status
  e2e/assets/status/chart-with-template-vars/Chart.yaml
  e2e/assets/status/chart-with-template-vars/fleet.yaml
  e2e/assets/status/chart-with-template-vars/templates/configmap.yaml
  e2e/assets/status/gitrepo.yaml
  e2e/single-cluster/gitrepo_test.go
  e2e/single-cluster/status_test.go
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
  internal/cmd/controller/reconciler/bundle_controller.go
Labels: kind/bug, kind/backport, JIRA

#3193 [backport v2.10] [SURE-9137] Add template errors to bundle and gitrepo status
  e2e/assets/status/chart-with-template-vars/Chart.yaml
  e2e/assets/status/chart-with-template-vars/fleet.yaml
  e2e/assets/status/chart-with-template-vars/templates/configmap.yaml
  e2e/assets/status/gitrepo.yaml
  e2e/single-cluster/gitrepo_test.go
  e2e/single-cluster/status_test.go
  internal/cmd/controller/gitops/reconciler/status_controller.go
  internal/cmd/controller/reconciler/bundle_controller.go
Labels: kind/bug, kind/backport, JIRA

#3203 Add resourceCounts and incomplete state to BundleDeploymentStatus
  charts/fleet-crd/templates/crds.yaml
  internal/cmd/agent/deployer/monitor/updatestatus.go
  internal/cmd/agent/deployer/monitor/updatestatus_test.go
  pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go
  pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
Labels: kind/bug

#3189 [CI/e2e] Adds definition of helmops metrics port
  dev/setup-k3d
  e2e/metrics/suite_test.go
Labels: area/ci

#3209 Add PerClusterResourceCounts to GitRepo status
  charts/fleet-crd/templates/crds.yaml
  internal/resourcestatus/resourcekey.go
  internal/resourcestatus/resourcekey_test.go
  pkg/apis/fleet.cattle.io/v1alpha1/status.go
  pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
Labels: kind/bug

#3239 [v0.10] - Always returns result with RequeueAfter set
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Labels: kind/bug

#3238 Rework how resources are calculated
  internal/resourcestatus/resourcekey.go
  internal/resourcestatus/resourcekey_test.go
Labels: kind/enhancement

#3257 [v0.11] - Always returns result with RequeueAfter set
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Labels: kind/backport

#3267 Add `templateValues` to HelmApp, Bundle, etc
  charts/fleet-crd/templates/crds.yaml
  internal/cmd/controller/options/calculate.go
  internal/cmd/controller/target/builder.go
  internal/cmd/controller/target/target_test.go
  pkg/apis/fleet.cattle.io/v1alpha1/bundledeployment_types.go
  pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
Labels: kind/enhancement
