Repository rancher/fleet, pull requests merged in 2025-02, with the labels that each got.

#3285 Remove finalizers on contents when uninstalling Fleet
  dev/remove-fleet
Labels: kind/bug, kind/chore

#3307 Always returns result with RequeueAfter set
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Labels: kind/bug

#3308 [v0.11] - Change ImageScanCommit in GitRepo spec to a pointer (#3302)
  internal/cmd/controller/imagescan/gitcommit_job.go
  pkg/apis/fleet.cattle.io/v1alpha1/gitrepo_types.go
  pkg/apis/fleet.cattle.io/v1alpha1/zz_generated.deepcopy.go
Labels: area/performance, kind/backport

#3337 Using a webhook sets the intervall to one hour again
  pkg/webhook/webhook.go
  pkg/webhook/webhook_test.go
Labels: kind/bug

#3368 Add extra error info when downloading remote charts
  integrationtests/cli/apply/helm_test.go
  internal/bundlereader/resources.go
Labels: kind/bug

#3362 Adds tolerations from fleet-controller Deployment
  charts/fleet/templates/rbac.yaml
  charts/fleet/templates/rbac_gitjob.yaml
  integrationtests/gitjob/controller/suite_test.go
  internal/cmd/controller/agentmanagement/controllers/bootstrap/bootstrap.go
  internal/cmd/controller/agentmanagement/controllers/controllers.go
  internal/cmd/controller/gitops/operator.go
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
  internal/cmd/controller/gitops/reconciler/gitjob_test.go
Labels: kind/bug

#3385 Adds message context to fleet apply errors
  integrationtests/cli/apply/helm_test.go
  internal/bundlereader/read.go
  internal/bundlereader/resources.go
  internal/cmd/cli/apply.go
  internal/cmd/cli/apply/apply.go
  internal/cmd/cli/gitcloner/cloner.go
  internal/cmd/cli/gitcloner/cloner_test.go
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
  internal/cmd/controller/gitops/reconciler/gitjob_test.go
Labels: kind/enhancement
