Repository rancher/fleet, pull requests merged in 2025-03, with the labels that each got.

#3416 [SURE-9419] Move agent registration into controller container
  charts/fleet-agent/templates/deployment.yaml
  e2e/multi-cluster/installation/agent_test.go
  internal/cmd/agent/operator.go
  internal/cmd/agent/register.go
  internal/cmd/agent/root.go
  internal/cmd/controller/agentmanagement/agent/manifest.go
Labels: kind/enhancement

#3434 [SURE-9419] Clean-up: Only fetch AgentInfo once
  internal/cmd/agent/clusterstatus.go
  internal/cmd/agent/operator.go
  internal/cmd/agent/register.go
  internal/cmd/agent/register/register.go
  internal/cmd/agent/root.go
Labels: kind/chore

#3464 Fix Rancher CA bundle mount after GitRepo update
  e2e/single-cluster/helm_auth_test.go
  internal/cmd/controller/gitops/reconciler/gitjob_controller.go
Labels: kind/bug
